### ISSUE TITLE
Failed to generate the picture

### ISSUE THREAD

**Issue by zhangjiale-64** [CawaMS/OutputCacheOpenAI#1]
**Describe the issue:**
In the browser launched, append /nocache/{your_description_for_a_picture} and /cached/{your_description_for_a_picture} did not generate the picture. The error is shown as following:
![image](https://github.com/CawaMS/OutputCacheOpenAI/assets/141405558/61b4116f-ff92-456b-adb4-2bc5e510e12b)

![image](https://github.com/CawaMS/OutputCacheOpenAI/assets/141405558/39bed8ec-a646-402e-914b-d9ed2e5af8b5)

**Repro Steps:**
1. Clone the code to local.
2. Open in Visual Studio.
3. Run `cd OutputCacheDallESample`.
4. Run `dotnet user-secrets init`.
5. Create Azure Cache for Redis and Azure Open AI resources in Azure.
6. Run
```
dotnet user-secrets set "RedisCacheConnection" "your_rediscache_connectionstring"

dotnet user-secrets set "apiUrl" "https://<your_openai_name>.openai.azure.com/openai/images/generations:submit?api-version=2023-06-01-preview"

dotnet user-secrets set "apiKey" "your_openai_api_key"
```
7. In a launched browser after debugging in Visual Studio, append /nocache/{your_description_for_a_picture} and /cached/{your_description_for_a_picture}

**Expected behavior:**
After appending /nocache/{your_description_for_a_picture} and /cached/{your_description_for_a_picture}, the web page can be opened normally.

@hemarina and @CawaMS for notification.

**Comment by CawaMS** [comment]
@zhangjiale-64 From the error stack, it reads the Redis Cache connection string config is empty. Can you please do 'dotnet run' command? Visual Studio uses a Secrets.json file to save the user secrets, which works differently from the dotnet command line.

**Comment by zhangjiale-64** [comment]
@CawaMS  This issue is indeed caused by my configuration. According to your suggestion, this issue will no longer be reproduced and we will close this issue.
